### PR TITLE
Derive FieldType for simple enums

### LINKED ISSUE #20: Support for simple enums of a single type
afaics, enums consisting of a single type are not yet automatically supported.  I can implement `ToSql`, but it would be nice to not need to.  I see there is a `#[butane_type(Text)]`, but it doesnt appear to help here.  I have serde `Serialize` and `Deserialize` for the enum, and `ToString`/`FromStr`, but I get the error below.

```rust
    #[derive(
        Clone,
        Copy,
        Debug,
        Deserialize,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd,
        Serialize,
    )]
    pub enum FormatEnum {
        #[serde(rename = "tif")]
        Tif,
        #[serde(rename = "png")]
        Png,
    }

    impl ToString for FormatEnum {
        fn to_string(&self) -> String {
            match *self {
                Self::Tif => "tif".to_string(),
                Self::Png => "png".to_string(),
            }
        }
    }

    impl std::str::FromStr for FormatEnum {
        type Err = &'static str;
        fn from_str(value: &str) -> Result<Self, Self::Err> {
            match value {
                "tif" => Ok(Self::Tif),
                "png" => Ok(Self::Png),
                _ => Err("invalid value"),
            }
        }
    }

    impl Default for FormatEnum {
        fn default() -> Self {
            FormatEnum::Tif
        }
    }
```
error:
```rust
error[E0277]: the trait bound `FormatEnum: ToSql` is not satisfied
   --> rust/models/src/lib.rs:388:5
    |
388 |     #[model]
    |     ^^^^^^^^ the trait `ToSql` is not implemented for `FormatEnum`
    |
    = help: the following other types implement trait `ToSql`:
              ...
            and 32 others
    = note: required for `std::option::Option<FormatEnum>` to implement `ToSql`
    = note: required for `SqlVal` to implement `From<std::option::Option<FormatEnum>>`
    = note: required for `std::option::Option<FormatEnum>` to implement `Into<SqlVal>`

```

enums are mentioned at https://github.com/Electron100/butane/blob/master/notes.org#roadmap

### PR DESCRIPTION
**Pull request by Electron100**
Support automatic deriving of `FieldType` for simple enums. The database representation is the string form of the variant name. This builds on the capability from #68 

Fixes #20

Future work could allow an option to use discriminant value instead of name.

### CODE REVIEW

**Comment by Electron100** [comment]
@jayvdb does this meet your needs for #20?

**Review by jayvdb — APPROVED** [review]

File: butane_codegen/src/lib.rs [hunk 1]
```diff
@@ -170,8 +170,82 @@ fn migrations_dir() -> PathBuf {
...
 #[proc_macro_derive(FieldType)]
 pub fn derive_field_type(input: TokenStream) -> TokenStream {
-    let ast = syn::parse_macro_input!(input as syn::DeriveInput);
-    derive_field_type_with_json(&ast.ident)
+    let derive_input = syn::parse_macro_input!(input as syn::DeriveInput);
+    let ident = &derive_input.ident;
+    match derive_input.data {
+        syn::Data::Struct(_) => derive_field_type_with_json(ident),
+        syn::Data::Enum(data_enum) => derive_field_type_for_enum(ident, data_enum),
+        syn::Data::Union(_) => panic!("Cannot derive FieldType for a union"),
```
Comment (jayvdb) [inline butane_codegen/src/lib.rs:178]: can we have this failure mode instead revert back to using `derive_field_type_with_json` ?

File: butane_codegen/src/lib.rs [hunk 2]
```diff
@@ -170,8 +170,82 @@ fn migrations_dir() -> PathBuf {
...
+    }
+}
+
+fn derive_field_type_for_enum(ident: &Ident, data_enum: syn::DataEnum) -> TokenStream {
+    data_enum.variants.iter().for_each(|variant| {
+        if variant.fields != syn::Fields::Unit {
+            panic!("Only simple enums are supported when deriving FieldType")
```
Comment (jayvdb) [inline butane_codegen/src/lib.rs:185]: can we have this failure mode instead revert back to using `derive_field_type_with_json` (if that feature is enabled) which does support complex enums?
